# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo welcomme to aws kubernetes cluster
  displayName: 'Run a multi-line script'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes/'
    backendServiceAWS: 'aws for terraform'
    backendAWSBucketName: 'terraform-backendstate-in28minutes-123'
    backendAWSKey: 'kubernetes-dev.tfstate'


# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'aws'
#     command: 'validate'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes/'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes/'
    environmentServiceNameAWS: 'aws for terraform'

