
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build_job
        steps:
          - bash: echo "Do the build"
  - stage: DevDploy
    jobs:
      - deployment: DevDeployjob
        environment: Dev
        strategy:
         runOnce:
           deploy:
            steps:
              - script: echo deploy to Dev
  - stage: QADploy
    jobs:
      - deployment: QADeployjob
        environment: QA
        strategy:
         runOnce:
           deploy:
            steps:
              - script: echo deploy to QA