
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build_job
        steps:
          - bash: echo "Do the build"
  - stage: Dev_Dploy
    jobs:
      - deployment: Dev-Deployj-ob
        environment: Dev
        strategy:
         runOnce:
           deploy:
            steps:
              - script: echo deploy to Dev
  - stage: QA_Dploy
    jobs:
      - deployment: QA-Deploy-job
        environment: QA
        strategy:
         runOnce:
           deploy:
            steps:
              - script: echo deploy to QA