
trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  steps:
  - script:  echo job1
    displayName: first job is successing

- job: job2
  steps:
  - script: echo job2
    displayName: second job is success