# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

# variables:
#   tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker_hub_connection'
        repository: 'bijuthomaspta / currency-exchange-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 351
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'
- stage: Deploy
  displayName: deploy image
  jobs:
    - job: deploy
      displayName:  Deploy
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifests'
          targetPath: '$(system.ArtifactStagingDirectory)'
  
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'Azure_kubernetes_connection-2'
          namespace: 'default'
          manifests: '$(system.ArtifactStagingDirectory)/configuration/kubernetes/deployment.yml'
          containers: 'bijuthomaspta / currency-exchange-devops:351'